
DROP TABLE project_worker IF EXISTS;
  DROP TABLE project IF EXISTS;
  DROP TABLE worker IF EXISTS;
DROP TABLE client IF EXISTS;
CREATE TABLE client (
    ID int PRIMARY KEY,
    NAME VARCHAR(1000),
    CHECK (LENGTH(NAME)>1 AND LENGTH(NAME)<=1000)
);

    CREATE TABLE worker (
    ID int PRIMARY KEY,
    NAME VARCHAR(1000),
    BIRTHDAY DATE,
       LEVEL VARCHAR(100) NOT NULL,
    SALARY int

     CHECK(BIRTHDAY>'1900-01-01' AND LENGTH(NAME)>1 AND LENGTH(NAME)<=1000 AND SALARY>=100 AND SALARY<=100000 AND LEVEL IN ('TRAINEE', 'JUNIOR', 'MIDDLE', 'SENIOR'))
    );


    CREATE TABLE project (
    ID INT  PRIMARY KEY,
    CLIENT_ID INT ,
    START_DATE DATE,
    FINISH_DATE DATE,
    FOREIGN KEY (CLIENT_ID) REFERENCES client(ID)
    );

    CREATE TABLE project_worker(
    PROJECT_ID INT ,
    WORKER_ID INT ,
    PRIMARY KEY(PROJECT_ID, WORKER_ID),
    FOREIGN KEY (PROJECT_ID)REFERENCES project(ID),
    FOREIGN KEY(WORKER_ID) REFERENCES worker(ID)
    );

